# Generated by Django 5.1.8 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_hub", "0090_merge_20260423_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrule",
            name="trigger_frequency",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
