# Generated by Django 5.1.8 on 2026-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0091_evaltemplateversion_snapshot_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaltemplate',
            name='output_type_normalized',
            field=models.CharField(blank=True, choices=[('pass_fail', 'Pass/Fail'), ('percentage', 'Percentage'), ('deterministic', 'Deterministic')], help_text='Normalized output type: pass_fail, percentage, deterministic', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaltemplateversion',
            name='choice_scores',
            field=models.JSONField(blank=True, help_text='Choice→score mapping at this version. NULL on pre-snapshot versions.', null=True),
        ),
        migrations.AlterField(
            model_name='evaltemplateversion',
            name='output_type_normalized',
            field=models.CharField(blank=True, choices=[('pass_fail', 'Pass/Fail'), ('percentage', 'Percentage'), ('deterministic', 'Deterministic')], help_text='Normalized output type at this version: pass_fail, percentage, deterministic. NULL on pre-snapshot versions.', max_length=20, null=True),
        ),
    ]
