# Generated by Django 5.1.8 on 2026-03-10 10:58

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_hub', '0059_alter_dataset_eval_reason_status'),
        ('tracer', '0046_replaysession'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE public.tracer_observation_span DROP COLUMN IF EXISTS system",
                    reverse_sql=(
                        "ALTER TABLE public.tracer_observation_span "
                        "ADD COLUMN IF NOT EXISTS system varchar(255) NULL"
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='observationspan',
                    name='system',
                ),
            ],
        ),
        migrations.AddField(
            model_name='observationspan',
            name='operation_name',
            field=models.CharField(blank=True, help_text='Operation type within span kind (e.g., chat, image_generation, speech_to_text)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='observationspan',
            name='resource_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Raw OTEL resource attributes (service.name, project info, etc.)'),
        ),
        migrations.AddField(
            model_name='observationspan',
            name='semconv_source',
            field=models.CharField(default='traceai', help_text='Semantic convention source: traceai, otel_genai, openinference, openllmetry', max_length=50),
        ),
        migrations.AddField(
            model_name='observationspan',
            name='span_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Raw OTEL span attributes in their original form. Stored for ClickHouse migration and future-proofing.'),
        ),
        migrations.AddField(
            model_name='observationspan',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='observationspan',
            index=django.contrib.postgres.indexes.GinIndex(fields=['span_attributes'], name='tracer_obse_span_at_gin'),
        ),
    ]
