# Generated by Django 5.1.8 on 2026-04-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0072_alter_traceerrorgroup_title_and_more'),
        ('tracer', '0072_saved_view_sessions_tab'),
    ]

    operations = [
    ]
