# Generated by Django 5.1.8 on 2026-05-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0073_merge_20260428_1653'),
        ('tracer', '0074_drop_unused_span_attribute_gin_indexes'),
    ]

    operations = [
    ]
